### ISSUE TITLE
Failed to parse basic string

### ISSUE THREAD

**Issue by Petah** [touv/node-csv-string#20]
```
var csv = require('csv-string');
console.log(csv.parse('"09/21/2015 12:59:31.613","6950.000000","3460.478409"'));
```

outputs

```
[]
```

**Comment by touv** [comment]
which node version ?

are you try 

```javascript
csv.parse(data, ",")
````

**Comment by Petah** [comment]
Pretty sure it was the latest (4.1), but yea specifying the delimiter worked.

**Comment by touv** [comment]
By default, the module tries to detect the separator (see.https://github.com/touv/node-csv-string/blob/master/lib/csv.js#L44-63)
maybe it's not a good choice ...
